### ISSUE TITLE
请问在 ArchLab 里，怎么以 GUI mode 来执行指令，我卡在了设置 DISPLAY 环境变量上，望回复

### ISSUE THREAD

**Issue by drivebyer** [Exely/CSAPP#2]

**Comment by Exely** [comment]
我没试过GUI，但在unix 上你要初始化`DISPLAY`变量，怎么设置可以找找教程，试试`export DISPLAY=:0`

**Comment by drivebyer** [comment]
> 我没试过GUI，但在unix 上你要初始化`DISPLAY`变量，怎么设置可以找找教程，试试`export DISPLAY=:0`

感谢您的回复，DISPLAY 环境变量我照着 Lab 里的手册设置了，还是没法打开 GUI 模式。

我看很少人用到了 GUI 模式，不过我发现这个 Lab 里提供的这个工具还挺有用的。只有自己慢慢折腾了。:smiley:
