### ISSUE TITLE
archlab中循环展开优化bug解决

### ISSUE THREAD

**Issue by xinghyfish** [Exely/CSAPP#9]
笔记中提到的archlab的Part C部分循环展开优化时，将8次展开和4次展开相结合出现的问题（参考文件`labs/archlab/sim/pipe/mncopy.ys`）应该是由于跳转的名称出现重复（8次和4词都从`ele1`开始编号，但是终止语句并不相同）导致问题。经过实验把4次循环的`ele`名称和之前的区分开来即可通过全部测试并将Average CPE降到8.64。

**Comment by Exely** [comment]
感谢！可以提交commit，我更新一下！

**Comment by xinghyfish** [comment]
收到，已经把fix之后的版本commit上去了

**Comment by Exely** [comment]
你有新的archlab结果的话可以再更新一下笔记😊

**Comment by xinghyfish** [comment]
好的😉
